name: CI

on:
  push:
    branches: 
    - main
    - Dev
    - Features/*
  pull_request:
    branches:
    - main
    - Dev
    - Features/*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test with the dotnet CLI
      run: dotnet test
    - uses: actions/upload-artifact@v2
      with:
       name: EvoNaplo
       path: EvoNaplo/EvoNaplo/bin/Release
